os: linux

services:
- mongodb

env:
    global:
    - MONGO_USERNAME="travis"
    - MONGO_PASSWORD="test"
    - APP_ID=APP_ID
    - APP_SECRET=APP_SECRET

language: python

python:
- 3.6
#- 3.7

install:
- pip install -r server/requirements.txt

before_script:
#- sleep 15
- mongo bilibili_bangumi --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
- python -m unittest server_tests/test_api.py
